### ISSUE TITLE
MonadEffect instance

### ISSUE THREAD

**Issue by jamesdbrock** [purescript/purescript-tailrec#28]
Would this work?

```haskell
instance monadEffectRec :: MonadEffect m => MonadRec m where
  tailRecM = liftEffect <<< tailRecM
```

**Comment by hdgarrood** [comment]
It wouldn’t, for two reasons:

- constraints aren’t used as part of solving, so this would essentially be saying that every type `m` has to have a MonadEffect instance in order to have a MonadRec instance, and it would overlap with every other instance 
- it wouldn’t achieve what you want. The idea of providing a `MonadRec m` instance is to allow people to write recursive monadic code in `m`. This would only let you write recursive monadic code in `Effect` and then lift it into `m`, but you can already do that anyway via Effect’s MonadRec instance.
